#!/bin/bash

# Check for Ubuntu
if [ "$os" != "blackhat" ]; then
    echo "=============================================="
    echo "Windows on Cloud Installed by @amjiddader"
    echo "For help create issue on below github repo."
    echo "https://github.com/amjiddader/windows-on-cloud"
    echo "==============================================="
   # exit 1
fi

# Function to download and install OS
install_os() {
    echo "Choose a CDN:"
    echo "1. wansaw.com  | Fast (Recommended)"
    echo "2. archive.org | Very Slow but stable"
    read -p "Enter CDN choice (1-2): " cdn_choice

    case $cdn_choice in
        1) cdn="master.dl.sourceforge.net/project/windows-on-cloud";;
        2) cdn="archive.org/download/windows11-tiny11-cloudvm";;
        *) echo "Invalid choice. Exiting."; exit 1;;
    esac

    echo "Choose the Windows version you want to install:"
    echo "1. Windows11 x64_en (DeBolted)"
    echo "2. Windows11 x64_en"
    echo "3. Windows10 x64_en (Buggy)"
    read -p "Choose your version (1-3): " os_version

    if ! [[ "$os_version" =~ ^[1-3]$ ]]; then
        echo "Invalid OS version. Exiting."
        exit 1
    fi

    # Get Windows logins...
    if [ "$os_version" == "1" ]; then
        lou="Amjid"
        lop="amjiddader"
        los="win_11.gz?viasf=1"
        lof="Windows11 (debolted)"
    elif [ "$os_version" == "2" ]; then
        lou="Administrator"
        lop="Thuonghai001"
        los="win11?viasf=1"
        lof="Windows11"
    else
        lou="Administrator"
        lop="P@ssword64"
        los="win10_en.gz?viasf=1"
        lof="Windows10"
    fi

    # Install aria2c
    #apt update
    #apt install -y aria2

    # Download OS image
    #mkdir -p /temp
    # aria2c --check-certificate=false -x 16 -s 16 "https://$cdn/$los" -o "windows.gz"

    # Automatically determine primary disk path
    #primary_disk=$(lsblk -no NAME,MOUNTPOINT | awk '$2=="/" {print $1}' | head -n 1)
    primary_disk=$(df -h /mnt | awk 'NR==2 {print $1}')

    echo "Installing Windows in $primary_disk"
    echo "If you want to install in another disk or if $primary_disk is not correct disk.."
    echo "Press CTRL+C to exit and Mount your disk then run installer again.."
    echo "If $primary_disk valid and mounted at root / mnt then continue.."
    echo "Continung in 5 secons..............."
    sleep 5
    if [ -z "$primary_disk" ]; then
        read -p "Could not detect the primary disk. Enter disk path where Windows will be installed (e.g., /dev/vda): " primary_disk
    fi

    # Install custom OS using dd and gunzip
    #gunzip -c "/temp/windows.gz" | dd of="$primary_disk" bs=4M
    # aria2c --check-certificate=false -x 16 -s 16 "https://$cdn/$los" -o - | gunzip -c | dd of="$primary_disk" bs=4M
    wget -O- "https://$cdn/$los" | dd of="$primary_disk" bs=4M

    echo "Thank you for using the windows-on-cloud installer..."
    echo "Install $lof but you may need to set up Networking"
    echo "Open your browser shell and change your network setting..."
    # Display installed OS info
    echo "Server Login Information:"
    echo "Username: $lou"
    echo "Password: $lop"
    echo "==============="
    if [ "$os_version" == "1" ]; then
        echo "This is a debolted version of windows 11."
        echo "Updates are disabled and all microsoft app are remove."
        echo "You need to manully install some VC++"
        echo "TightVNC Password: amjiddader"
    fi
    echo "=============="
    echo "For help, check https://github.com/amjiddader/windows-on-cloud"
    echo "Friendly Advice: (this script is clear and unencrypted) But Running scripts from the internet without verifying their content can be risky.. "
    sleep 2
}

# Main script execution
install_os
